name: Test Quickstart

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pixi (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install pixi (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          powershell -ExecutionPolicy ByPass -c "irm -useb https://pixi.sh/install.ps1 | iex"
          echo "$HOME/.pixi/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run quickstart
        shell: bash
        run: |
          pixi run quickstart
